RESULT = hw1
SOURCES = \
  hw1.mli hw1.ml \
  test_hw1.ml \
  hw1_reduction.mli hw1_reduction.ml \
  test_hw1_reduction.ml

all: nc

OCAMLMAKEFILE = ../ocaml-makefile/OCamlMakefile
include $(OCAMLMAKEFILE)