RESULT = hw2
SOURCES = \
  ../hw1/hw1.mli ../hw1/hw1.ml \
  ../hw1/hw1_reduction.mli ../hw1/hw1_reduction.ml \
  hw2_inference.mli hw2_inference.ml \
  test_hw2_inference.ml \
  hw2_unify.mli hw2_unify.ml \
  test_hw2_unify.ml

all: nc

OCAMLMAKEFILE = ../ocaml-makefile/OCamlMakefile
include $(OCAMLMAKEFILE)